In [ ]:
import torch
import numpy as np

In [ ]:
input = np.array([1,2,3])
model = np.array([0.1,0.2,0.3])
result = 10
pred = input@model

np.power(result - pred,2)

73.96

#Reinforcemet learning

In [ ]:
model = np.array([-0.50191485,  0.84416303,  0.67852961])

In [ ]:
for i in range(5):
  random = np.random.random(3)-0.5
  evolution = model + random
  pred = input@evolution
  print(evolution)
  print(np.power(result - pred,2))


[-0.77886883  0.49944948  1.12666052]
40.959850098708706
[-0.01934433  0.56514559  0.39547204]
59.33061694718393
[-0.52258396  1.04628781  1.01455704]
29.01262877119636
[-0.0545801   1.26240389  0.68634383]
29.92900531650941
[-0.97610286  0.86778555  0.42981174]
63.21993647204063


#For kids

x*1+2*y+3*z=10

In [ ]:
input

array([1, 2, 3])

In [ ]:
ten_input = torch.from_numpy(input.astype(np.float32))
model_input = torch.nn.Parameter(torch.from_numpy(model))

In [ ]:
model_input = torch.nn.Parameter(model_input)

class Net(torch.nn.Module):
  def __init__(self, model_input,result=10):
    super().__init__()
    self.layer = torch.nn.Linear(3, 1)
    self.result = result
  def forward(self, observation):
    x = self.layer(observation)
    loss = torch.pow( self.result - x,2)
    return loss
mod_torch = Net(torch.from_numpy(model))
gen = iter(mod_torch.layer.parameters())
print(next(gen))
optimizer = torch.optim.SGD(mod_torch.parameters(), lr=0.01, momentum=0.9)

Parameter containing:
tensor([[-0.3886, -0.4944,  0.5726]], requires_grad=True)


In [ ]:

class Consumption(torch.nn.Module):
  def __init__(self):
    super().__init__()
    

In [ ]:
gen = iter(mod_torch.layer.parameters())
print(next(gen))

Parameter containing:
tensor([[-0.2030, -0.1231,  1.1295]], requires_grad=True)


In [ ]:
optimizer.zero_grad()

In [ ]:
pred = mod_torch(ten_input)
print(pred)
loss = torch.pow(result - pred,2)
print(loss)

tensor([6.7326], grad_fn=<AddBackward0>)
tensor([10.6762], grad_fn=<PowBackward0>)


In [ ]:
loss.backward()
optimizer.step()

In [ ]:
hours = list()
for i in range(24):
  obs = np.random.random(5)
  hours.append(obs)

In [ ]:

class Consumption_model(torch.nn.Module):
  def __init__(self):
    super().__init__()
    self.layer1 = torch.nn.Linear(5, 2)
    self.layer2 = torch.nn.Linear(2, 1)

  def forward(self, observations):
    x = self.layer1(observations)
    action = self.layer2(x)
    return action  

cons_model = Consumption_model()
optimizer = torch.optim.SGD(cons_model.parameters(), lr=0.0001, momentum=0.9)

In [ ]:
actions = list()
for obs in hours:
  obs_torch = torch.from_numpy(obs.astype(np.float32))
  action = cons_model(obs_torch)
  actions.append(action)

def cost_func(actions):
  cost = 0
  for i in actions:
    cost+=i
  return torch.pow(cost,2)
cost = cost_func(actions)
cost

tensor([0.0558], grad_fn=<PowBackward0>)

In [ ]:
cost.backward()
optimizer.step()
optimizer.zero_grad()